<?php

namespace Database\Seeders;

use App\Enums\ListingCondition;
use App\Enums\ListingStatus;
use App\Models\Category;
use App\Models\Listing;
use App\Models\ListingImage;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class ListingSeeder extends Seeder
{
    public function run(): void
    {
        $owners = User::whereIn('email', [
            'owner@tala.test',
            'ben.tennyson@lendly.test',
            'gumball.watterson@lendly.test',
            'finn.mertens@lendly.test',
            'marceline.abadeer@lendly.test',
            'steven.universe@lendly.test',
            'nigel.uno@lendly.test',
            'wallabee.beetles@lendly.test',
            'blossom.utonium@lendly.test',
            'johnny.bravo@lendly.test',
            'samurai.jack@lendly.test',
        ])->get()->keyBy('email');

        if ($owners->isEmpty()) {
            return;
        }

        $samples = [
            [
                'category' => 'Tools & Equipment',
                'subcategory' => 'Pressure Washers',
                'name' => 'Bosch Pressure Washer',
                'brand' => 'Bosch',
                'condition' => ListingCondition::Excellent,
                'estimated_original_price' => 8000,
                'price_per_day' => 450,
                'security_deposit' => 1000,
                'location' => 'Batangas City',
                'latitude' => 13.7565,
                'longitude' => 121.0583,
                'max_rental_duration_days' => 7,
                'description' => 'Powerful electric pressure washer, great for cleaning cars, patios, and driveways.',
                'color' => '#2563EB',
                'owner_email' => 'owner@tala.test',
            ],
            [
                'category' => 'Photography & Video',
                'subcategory' => 'Cameras',
                'name' => 'Canon EOS M50 Mirrorless Camera',
                'brand' => 'Canon',
                'condition' => ListingCondition::LikeNew,
                'estimated_original_price' => 35000,
                'price_per_day' => 800,
                'security_deposit' => 5000,
                'location' => 'Lipa City, Batangas',
                'latitude' => 13.9411,
                'longitude' => 121.1622,
                'max_rental_duration_days' => 5,
                'description' => 'Compact mirrorless camera with 4K video, perfect for events and travel vlogging.',
                'color' => '#1E3A8A',
                'owner_email' => 'ben.tennyson@lendly.test',
            ],
            [
                'category' => 'Outdoor & Sports',
                'subcategory' => 'Camping Gear',
                'name' => '4-Person Camping Tent',
                'brand' => 'Coleman',
                'condition' => ListingCondition::Good,
                'estimated_original_price' => 6000,
                'price_per_day' => 300,
                'security_deposit' => 500,
                'location' => 'Tanauan City, Batangas',
                'latitude' => 14.0866,
                'longitude' => 121.1497,
                'max_rental_duration_days' => 10,
                'description' => 'Spacious weatherproof tent, easy to set up, ideal for weekend camping trips.',
                'color' => '#0EA5E9',
                'owner_email' => 'gumball.watterson@lendly.test',
            ],
            [
                'category' => 'Events & Party',
                'subcategory' => 'Sound Systems',
                'name' => 'JBL PartyBox Speaker Set',
                'brand' => 'JBL',
                'condition' => ListingCondition::Excellent,
                'estimated_original_price' => 15000,
                'price_per_day' => 700,
                'security_deposit' => 2000,
                'location' => 'Sto. Tomas, Batangas',
                'latitude' => 14.1078,
                'longitude' => 121.1414,
                'max_rental_duration_days' => 3,
                'description' => 'Loud, portable party speakers with built-in lights, ideal for birthdays and small events.',
                'color' => '#4338CA',
                'owner_email' => 'finn.mertens@lendly.test',
            ],
            [
                'category' => 'Vehicles',
                'subcategory' => 'Motorcycles',
                'name' => 'Honda Click 125i Scooter',
                'brand' => 'Honda',
                'condition' => ListingCondition::Good,
                'estimated_original_price' => 90000,
                'price_per_day' => 900,
                'security_deposit' => 8000,
                'location' => 'Nasugbu, Batangas',
                'latitude' => 14.0722,
                'longitude' => 120.6317,
                'max_rental_duration_days' => 14,
                'description' => 'Fuel-efficient automatic scooter, well maintained, complete with two helmets.',
                'color' => '#1D4ED8',
                'owner_email' => 'marceline.abadeer@lendly.test',
            ],
            [
                'category' => 'Electronics',
                'subcategory' => 'Projectors',
                'name' => 'Epson Home Cinema Projector',
                'brand' => 'Epson',
                'condition' => ListingCondition::LikeNew,
                'estimated_original_price' => 28000,
                'price_per_day' => 600,
                'security_deposit' => 3000,
                'location' => 'Taal, Batangas',
                'latitude' => 13.8783,
                'longitude' => 120.9986,
                'max_rental_duration_days' => 5,
                'description' => 'Bright full-HD projector, perfect for movie nights and small presentations.',
                'color' => '#0369A1',
                'owner_email' => 'steven.universe@lendly.test',
            ],
            [
                'category' => 'Home Appliances',
                'subcategory' => 'Kitchen Appliances',
                'name' => 'KitchenAid Stand Mixer',
                'brand' => 'KitchenAid',
                'condition' => ListingCondition::Excellent,
                'estimated_original_price' => 22000,
                'price_per_day' => 350,
                'security_deposit' => 1500,
                'location' => 'Lemery, Batangas',
                'latitude' => 13.9139,
                'longitude' => 120.8825,
                'max_rental_duration_days' => 7,
                'description' => 'Heavy-duty stand mixer, great for baking projects and small home bakeries.',
                'color' => '#3B82F6',
                'owner_email' => 'nigel.uno@lendly.test',
            ],
            [
                'category' => 'Outdoor & Sports',
                'subcategory' => 'Bicycles',
                'name' => 'Trek Mountain Bike',
                'brand' => 'Trek',
                'condition' => ListingCondition::Good,
                'estimated_original_price' => 32000,
                'price_per_day' => 500,
                'security_deposit' => 3000,
                'location' => 'San Juan, Batangas',
                'latitude' => 13.8275,
                'longitude' => 121.3958,
                'max_rental_duration_days' => 7,
                'description' => 'Sturdy mountain bike with front suspension, ready for trail rides.',
                'color' => '#2563EB',
                'owner_email' => 'wallabee.beetles@lendly.test',
            ],
            [
                'category' => 'Tools & Equipment',
                'subcategory' => 'Power Tools',
                'name' => 'DeWalt Cordless Drill Set',
                'brand' => 'DeWalt',
                'condition' => ListingCondition::Excellent,
                'estimated_original_price' => 12000,
                'price_per_day' => 350,
                'security_deposit' => 800,
                'location' => 'Bauan, Batangas',
                'latitude' => 13.7925,
                'longitude' => 121.0083,
                'max_rental_duration_days' => 7,
                'description' => 'Cordless drill/driver combo kit with two batteries and a carrying case.',
                'color' => '#F59E0B',
                'owner_email' => 'blossom.utonium@lendly.test',
            ],
            [
                'category' => 'Tools & Equipment',
                'subcategory' => 'Ladders',
                'name' => 'Aluminum Extension Ladder 12ft',
                'brand' => 'Werner',
                'condition' => ListingCondition::Good,
                'estimated_original_price' => 5000,
                'price_per_day' => 200,
                'security_deposit' => 300,
                'location' => 'Calaca, Batangas',
                'latitude' => 13.9319,
                'longitude' => 120.8144,
                'max_rental_duration_days' => 5,
                'description' => 'Lightweight aluminum extension ladder, safe up to 250 lbs.',
                'color' => '#64748B',
                'owner_email' => 'johnny.bravo@lendly.test',
            ],
            [
                'category' => 'Photography & Video',
                'subcategory' => 'Lenses',
                'name' => 'Sony 50mm f1.8 Lens',
                'brand' => 'Sony',
                'condition' => ListingCondition::LikeNew,
                'estimated_original_price' => 15000,
                'price_per_day' => 400,
                'security_deposit' => 3000,
                'location' => 'Calatagan, Batangas',
                'latitude' => 13.8306,
                'longitude' => 120.6325,
                'max_rental_duration_days' => 5,
                'description' => 'Fast prime lens, great for portraits and low-light shooting.',
                'color' => '#111827',
                'owner_email' => 'samurai.jack@lendly.test',
            ],
            [
                'category' => 'Photography & Video',
                'subcategory' => 'Lighting',
                'name' => 'Godox Studio Light Kit',
                'brand' => 'Godox',
                'condition' => ListingCondition::Excellent,
                'estimated_original_price' => 18000,
                'price_per_day' => 500,
                'security_deposit' => 2000,
                'location' => 'Lian, Batangas',
                'latitude' => 14.0392,
                'longitude' => 120.6417,
                'max_rental_duration_days' => 5,
                'description' => 'Two-softbox studio lighting kit with stands, ideal for product photography.',
                'color' => '#7C3AED',
                'owner_email' => 'owner@tala.test',
            ],
            [
                'category' => 'Events & Party',
                'subcategory' => 'Tents & Canopies',
                'name' => '10x10 Event Canopy Tent',
                'brand' => 'Coleman',
                'condition' => ListingCondition::Good,
                'estimated_original_price' => 9000,
                'price_per_day' => 400,
                'security_deposit' => 1000,
                'location' => 'Mabini, Batangas',
                'latitude' => 13.7472,
                'longitude' => 120.9214,
                'max_rental_duration_days' => 3,
                'description' => 'Pop-up canopy tent, great for outdoor parties, market stalls, and events.',
                'color' => '#DC2626',
                'owner_email' => 'ben.tennyson@lendly.test',
            ],
            [
                'category' => 'Events & Party',
                'subcategory' => 'Decor',
                'name' => 'LED Balloon Arch Kit',
                'brand' => 'Generic',
                'condition' => ListingCondition::Excellent,
                'estimated_original_price' => 4000,
                'price_per_day' => 250,
                'security_deposit' => 300,
                'location' => 'Tuy, Batangas',
                'latitude' => 13.9928,
                'longitude' => 120.7275,
                'max_rental_duration_days' => 3,
                'description' => 'Reusable balloon arch frame with LED string lights, easy setup.',
                'color' => '#DB2777',
                'owner_email' => 'gumball.watterson@lendly.test',
            ],
            [
                'category' => 'Outdoor & Sports',
                'subcategory' => 'Water Sports',
                'name' => 'Inflatable Kayak 2-Seater',
                'brand' => 'Intex',
                'condition' => ListingCondition::Good,
                'estimated_original_price' => 10000,
                'price_per_day' => 450,
                'security_deposit' => 1500,
                'location' => 'Rosario, Batangas',
                'latitude' => 13.8461,
                'longitude' => 121.2094,
                'max_rental_duration_days' => 3,
                'description' => 'Two-person inflatable kayak with paddles and a foot pump, packs into a duffel bag.',
                'color' => '#0EA5E9',
                'owner_email' => 'finn.mertens@lendly.test',
            ],
            [
                'category' => 'Vehicles',
                'subcategory' => 'Cars',
                'name' => 'Toyota Vios 2022',
                'brand' => 'Toyota',
                'condition' => ListingCondition::Excellent,
                'estimated_original_price' => 750000,
                'price_per_day' => 2000,
                'security_deposit' => 15000,
                'location' => 'San Jose, Batangas',
                'latitude' => 13.8792,
                'longitude' => 121.1058,
                'max_rental_duration_days' => 10,
                'description' => 'Fuel-efficient sedan, automatic transmission, well-maintained with complete documents.',
                'color' => '#1E3A8A',
                'owner_email' => 'marceline.abadeer@lendly.test',
            ],
            [
                'category' => 'Electronics',
                'subcategory' => 'Drones',
                'name' => 'DJI Mini 3 Pro Drone',
                'brand' => 'DJI',
                'condition' => ListingCondition::LikeNew,
                'estimated_original_price' => 45000,
                'price_per_day' => 900,
                'security_deposit' => 5000,
                'location' => 'Ibaan, Batangas',
                'latitude' => 13.8189,
                'longitude' => 121.1339,
                'max_rental_duration_days' => 3,
                'description' => 'Compact 4K drone with obstacle avoidance, extra battery included.',
                'color' => '#334155',
                'owner_email' => 'steven.universe@lendly.test',
            ],
            [
                'category' => 'Home Appliances',
                'subcategory' => 'Cleaning Equipment',
                'name' => 'Karcher Steam Cleaner',
                'brand' => 'Karcher',
                'condition' => ListingCondition::Good,
                'estimated_original_price' => 7000,
                'price_per_day' => 300,
                'security_deposit' => 500,
                'location' => 'Cuenca, Batangas',
                'latitude' => 13.9014,
                'longitude' => 121.0525,
                'max_rental_duration_days' => 5,
                'description' => 'High-powered steam cleaner for upholstery, tiles, and kitchen surfaces.',
                'color' => '#059669',
                'owner_email' => 'nigel.uno@lendly.test',
            ],
            [
                'category' => 'Tools & Equipment',
                'subcategory' => 'Power Tools',
                'name' => 'Makita Angle Grinder',
                'brand' => 'Makita',
                'condition' => ListingCondition::Good,
                'estimated_original_price' => 6000,
                'price_per_day' => 250,
                'security_deposit' => 500,
                'location' => 'Malvar, Batangas',
                'latitude' => 14.0522,
                'longitude' => 121.1583,
                'max_rental_duration_days' => 5,
                'description' => 'Compact angle grinder for cutting and grinding metal, tile, and concrete.',
                'color' => '#EA580C',
                'owner_email' => 'wallabee.beetles@lendly.test',
            ],
            [
                'category' => 'Tools & Equipment',
                'subcategory' => 'Pressure Washers',
                'name' => 'Karcher K5 Pressure Washer',
                'brand' => 'Karcher',
                'condition' => ListingCondition::LikeNew,
                'estimated_original_price' => 12000,
                'price_per_day' => 500,
                'security_deposit' => 1200,
                'location' => 'Batangas City',
                'latitude' => 13.7565,
                'longitude' => 121.0583,
                'max_rental_duration_days' => 7,
                'description' => 'High-pressure electric washer with patio cleaner attachment, barely used.',
                'color' => '#2563EB',
                'owner_email' => 'blossom.utonium@lendly.test',
            ],
            [
                'category' => 'Tools & Equipment',
                'subcategory' => 'Ladders',
                'name' => 'Step Ladder 6ft',
                'brand' => 'Werner',
                'condition' => ListingCondition::Good,
                'estimated_original_price' => 2500,
                'price_per_day' => 150,
                'security_deposit' => 200,
                'location' => 'Lipa City, Batangas',
                'latitude' => 13.9411,
                'longitude' => 121.1622,
                'max_rental_duration_days' => 5,
                'description' => 'Sturdy A-frame step ladder, ideal for home repairs and painting jobs.',
                'color' => '#64748B',
                'owner_email' => 'johnny.bravo@lendly.test',
            ],
            [
                'category' => 'Photography & Video',
                'subcategory' => 'Cameras',
                'name' => 'Sony A7III Mirrorless Camera',
                'brand' => 'Sony',
                'condition' => ListingCondition::Excellent,
                'estimated_original_price' => 90000,
                'price_per_day' => 1500,
                'security_deposit' => 10000,
                'location' => 'Tanauan City, Batangas',
                'latitude' => 14.0866,
                'longitude' => 121.1497,
                'max_rental_duration_days' => 5,
                'description' => 'Full-frame mirrorless camera, excellent low-light performance, body only.',
                'color' => '#1E3A8A',
                'owner_email' => 'samurai.jack@lendly.test',
            ],
            [
                'category' => 'Photography & Video',
                'subcategory' => 'Lenses',
                'name' => 'Canon 24-70mm f2.8 Lens',
                'brand' => 'Canon',
                'condition' => ListingCondition::Excellent,
                'estimated_original_price' => 60000,
                'price_per_day' => 900,
                'security_deposit' => 8000,
                'location' => 'Sto. Tomas, Batangas',
                'latitude' => 14.1078,
                'longitude' => 121.1414,
                'max_rental_duration_days' => 5,
                'description' => 'Professional standard zoom lens, sharp across the whole range, well maintained.',
                'color' => '#111827',
                'owner_email' => 'owner@tala.test',
            ],
            [
                'category' => 'Photography & Video',
                'subcategory' => 'Lighting',
                'name' => 'Neewer Ring Light Kit',
                'brand' => 'Neewer',
                'condition' => ListingCondition::Good,
                'estimated_original_price' => 5000,
                'price_per_day' => 250,
                'security_deposit' => 500,
                'location' => 'Nasugbu, Batangas',
                'latitude' => 14.0722,
                'longitude' => 120.6317,
                'max_rental_duration_days' => 5,
                'description' => '18-inch LED ring light with stand and phone holder, great for content creation.',
                'color' => '#7C3AED',
                'owner_email' => 'ben.tennyson@lendly.test',
            ],
            [
                'category' => 'Events & Party',
                'subcategory' => 'Tents & Canopies',
                'name' => 'White Wedding Tent 20x30',
                'brand' => 'Generic',
                'condition' => ListingCondition::Good,
                'estimated_original_price' => 40000,
                'price_per_day' => 1500,
                'security_deposit' => 5000,
                'location' => 'Taal, Batangas',
                'latitude' => 13.8783,
                'longitude' => 120.9986,
                'max_rental_duration_days' => 3,
                'description' => 'Large white event tent, seats up to 60 guests, includes side walls.',
                'color' => '#DC2626',
                'owner_email' => 'gumball.watterson@lendly.test',
            ],
            [
                'category' => 'Events & Party',
                'subcategory' => 'Sound Systems',
                'name' => 'Bose S1 Pro PA System',
                'brand' => 'Bose',
                'condition' => ListingCondition::Excellent,
                'estimated_original_price' => 30000,
                'price_per_day' => 1000,
                'security_deposit' => 3000,
                'location' => 'Lemery, Batangas',
                'latitude' => 13.9139,
                'longitude' => 120.8825,
                'max_rental_duration_days' => 3,
                'description' => 'Portable battery-powered PA speaker, clear sound for small gatherings and speeches.',
                'color' => '#4338CA',
                'owner_email' => 'finn.mertens@lendly.test',
            ],
            [
                'category' => 'Events & Party',
                'subcategory' => 'Decor',
                'name' => 'Backdrop Stand with Fairy Lights',
                'brand' => 'Generic',
                'condition' => ListingCondition::Good,
                'estimated_original_price' => 3000,
                'price_per_day' => 200,
                'security_deposit' => 200,
                'location' => 'San Juan, Batangas',
                'latitude' => 13.8275,
                'longitude' => 121.3958,
                'max_rental_duration_days' => 3,
                'description' => 'Adjustable backdrop stand with warm fairy lights, perfect for photo corners.',
                'color' => '#DB2777',
                'owner_email' => 'marceline.abadeer@lendly.test',
            ],
            [
                'category' => 'Outdoor & Sports',
                'subcategory' => 'Camping Gear',
                'name' => '8-Person Family Tent',
                'brand' => 'Coleman',
                'condition' => ListingCondition::Excellent,
                'estimated_original_price' => 12000,
                'price_per_day' => 500,
                'security_deposit' => 1000,
                'location' => 'Bauan, Batangas',
                'latitude' => 13.7925,
                'longitude' => 121.0083,
                'max_rental_duration_days' => 10,
                'description' => 'Roomy family-sized tent with room divider, great for group camping trips.',
                'color' => '#0EA5E9',
                'owner_email' => 'steven.universe@lendly.test',
            ],
            [
                'category' => 'Outdoor & Sports',
                'subcategory' => 'Bicycles',
                'name' => 'Foldable City Bike',
                'brand' => 'Dahon',
                'condition' => ListingCondition::Good,
                'estimated_original_price' => 15000,
                'price_per_day' => 300,
                'security_deposit' => 1500,
                'location' => 'Calaca, Batangas',
                'latitude' => 13.9319,
                'longitude' => 120.8144,
                'max_rental_duration_days' => 7,
                'description' => 'Compact foldable bike, easy to carry and store, good for commuting.',
                'color' => '#2563EB',
                'owner_email' => 'nigel.uno@lendly.test',
            ],
            [
                'category' => 'Outdoor & Sports',
                'subcategory' => 'Water Sports',
                'name' => 'Stand Up Paddleboard',
                'brand' => 'Bestway',
                'condition' => ListingCondition::Good,
                'estimated_original_price' => 12000,
                'price_per_day' => 500,
                'security_deposit' => 2000,
                'location' => 'Calatagan, Batangas',
                'latitude' => 13.8306,
                'longitude' => 120.6325,
                'max_rental_duration_days' => 3,
                'description' => 'Inflatable SUP board with paddle and pump, includes carry backpack.',
                'color' => '#0EA5E9',
                'owner_email' => 'wallabee.beetles@lendly.test',
            ],
            [
                'category' => 'Vehicles',
                'subcategory' => 'Cars',
                'name' => 'Mitsubishi Xpander 2023',
                'brand' => 'Mitsubishi',
                'condition' => ListingCondition::Excellent,
                'estimated_original_price' => 1100000,
                'price_per_day' => 2800,
                'security_deposit' => 20000,
                'location' => 'Lian, Batangas',
                'latitude' => 14.0392,
                'longitude' => 120.6417,
                'max_rental_duration_days' => 10,
                'description' => '7-seater MPV, automatic transmission, ideal for family trips and group travel.',
                'color' => '#1E3A8A',
                'owner_email' => 'blossom.utonium@lendly.test',
            ],
            [
                'category' => 'Vehicles',
                'subcategory' => 'Motorcycles',
                'name' => 'Yamaha Mio 125 Scooter',
                'brand' => 'Yamaha',
                'condition' => ListingCondition::Good,
                'estimated_original_price' => 75000,
                'price_per_day' => 700,
                'security_deposit' => 6000,
                'location' => 'Mabini, Batangas',
                'latitude' => 13.7472,
                'longitude' => 120.9214,
                'max_rental_duration_days' => 14,
                'description' => 'Reliable automatic scooter, good on fuel, comes with one helmet.',
                'color' => '#1D4ED8',
                'owner_email' => 'johnny.bravo@lendly.test',
            ],
            [
                'category' => 'Electronics',
                'subcategory' => 'Projectors',
                'name' => 'BenQ Portable Projector',
                'brand' => 'BenQ',
                'condition' => ListingCondition::LikeNew,
                'estimated_original_price' => 20000,
                'price_per_day' => 450,
                'security_deposit' => 2000,
                'location' => 'Tuy, Batangas',
                'latitude' => 13.9928,
                'longitude' => 120.7275,
                'max_rental_duration_days' => 5,
                'description' => 'Compact portable projector with built-in speaker, great for outdoor movie nights.',
                'color' => '#0369A1',
                'owner_email' => 'samurai.jack@lendly.test',
            ],
            [
                'category' => 'Electronics',
                'subcategory' => 'Drones',
                'name' => 'DJI Air 2S Drone',
                'brand' => 'DJI',
                'condition' => ListingCondition::Excellent,
                'estimated_original_price' => 65000,
                'price_per_day' => 1200,
                'security_deposit' => 7000,
                'location' => 'Rosario, Batangas',
                'latitude' => 13.8461,
                'longitude' => 121.2094,
                'max_rental_duration_days' => 3,
                'description' => '1-inch sensor drone with 5.4K video, extra battery and ND filters included.',
                'color' => '#334155',
                'owner_email' => 'owner@tala.test',
            ],
            [
                'category' => 'Home Appliances',
                'subcategory' => 'Cleaning Equipment',
                'name' => 'Robot Vacuum Cleaner',
                'brand' => 'Xiaomi',
                'condition' => ListingCondition::Good,
                'estimated_original_price' => 15000,
                'price_per_day' => 350,
                'security_deposit' => 1500,
                'location' => 'San Jose, Batangas',
                'latitude' => 13.8792,
                'longitude' => 121.1058,
                'max_rental_duration_days' => 5,
                'description' => 'Smart robot vacuum with app control and auto-recharge dock.',
                'color' => '#059669',
                'owner_email' => 'ben.tennyson@lendly.test',
            ],
            [
                'category' => 'Home Appliances',
                'subcategory' => 'Kitchen Appliances',
                'name' => 'NutriBullet Blender Set',
                'brand' => 'NutriBullet',
                'condition' => ListingCondition::Excellent,
                'estimated_original_price' => 5000,
                'price_per_day' => 200,
                'security_deposit' => 300,
                'location' => 'Ibaan, Batangas',
                'latitude' => 13.8189,
                'longitude' => 121.1339,
                'max_rental_duration_days' => 5,
                'description' => 'Personal blender set with multiple cup sizes, great for smoothies and shakes.',
                'color' => '#3B82F6',
                'owner_email' => 'gumball.watterson@lendly.test',
            ],
            [
                'category' => 'Tools & Equipment',
                'subcategory' => 'Power Tools',
                'name' => 'Bosch Circular Saw',
                'brand' => 'Bosch',
                'condition' => ListingCondition::Good,
                'estimated_original_price' => 8000,
                'price_per_day' => 300,
                'security_deposit' => 700,
                'location' => 'Cuenca, Batangas',
                'latitude' => 13.9014,
                'longitude' => 121.0525,
                'max_rental_duration_days' => 5,
                'description' => 'Corded circular saw for clean, straight cuts on wood and plywood.',
                'color' => '#EA580C',
                'owner_email' => 'finn.mertens@lendly.test',
            ],
            [
                'category' => 'Photography & Video',
                'subcategory' => 'Cameras',
                'name' => 'GoPro Hero 11',
                'brand' => 'GoPro',
                'condition' => ListingCondition::LikeNew,
                'estimated_original_price' => 25000,
                'price_per_day' => 600,
                'security_deposit' => 2500,
                'location' => 'Malvar, Batangas',
                'latitude' => 14.0522,
                'longitude' => 121.1583,
                'max_rental_duration_days' => 5,
                'description' => 'Rugged action camera with mounts, perfect for beach trips and water sports.',
                'color' => '#1E3A8A',
                'owner_email' => 'marceline.abadeer@lendly.test',
            ],
        ];

        foreach ($samples as $sample) {
            $owner = $owners->get($sample['owner_email']);

            if (! $owner) {
                continue;
            }

            $category = Category::where('name', $sample['category'])->first();
            $subcategory = Category::where('name', $sample['subcategory'])->first();

            $listing = Listing::create([
                'owner_id' => $owner->id,
                'category_id' => $category->id,
                'subcategory_id' => $subcategory?->id,
                'name' => $sample['name'],
                'brand' => $sample['brand'],
                'description' => $sample['description'],
                'condition' => $sample['condition'],
                'estimated_original_price' => $sample['estimated_original_price'],
                'price_per_day' => $sample['price_per_day'],
                'security_deposit' => $sample['security_deposit'],
                'location' => $sample['location'],
                'latitude' => $sample['latitude'],
                'longitude' => $sample['longitude'],
                'max_rental_duration_days' => $sample['max_rental_duration_days'],
                'status' => ListingStatus::Published,
            ]);

            $this->attachPlaceholderImages($listing, $sample['name'], $sample['color']);
        }
    }

    /**
     * Generates simple SVG placeholder photos for a listing. The dev/test
     * environment has neither GD nor Imagick installed, so raster images
     * can't be generated on the fly — SVG is a valid <img> source and needs
     * no image extension, only string templating.
     */
    private function attachPlaceholderImages(Listing $listing, string $name, string $color): void
    {
        $slug = Str::slug($name);

        foreach (range(1, 2) as $i) {
            $svg = $this->placeholderSvg($name, $color, $i);
            $path = "listings/{$slug}-{$i}.svg";

            Storage::disk('public')->put($path, $svg);

            ListingImage::create([
                'listing_id' => $listing->id,
                'path' => $path,
                'sort_order' => $i - 1,
            ]);
        }
    }

    private function placeholderSvg(string $name, string $color, int $variant): string
    {
        $label = htmlspecialchars($name, ENT_QUOTES);
        $shade = $variant === 1 ? $color : $this->darken($color, 0.15);

        return <<<SVG
        <svg xmlns="http://www.w3.org/2000/svg" width="800" height="600" viewBox="0 0 800 600">
            <rect width="800" height="600" fill="{$shade}" />
            <circle cx="680" cy="80" r="140" fill="#ffffff" opacity="0.08" />
            <circle cx="90" cy="520" r="180" fill="#ffffff" opacity="0.08" />
            <text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle"
                  font-family="Arial, sans-serif" font-size="36" font-weight="700" fill="#ffffff">
                {$label}
            </text>
        </svg>
        SVG;
    }

    private function darken(string $hex, float $amount): string
    {
        $hex = ltrim($hex, '#');
        $r = hexdec(substr($hex, 0, 2));
        $g = hexdec(substr($hex, 2, 2));
        $b = hexdec(substr($hex, 4, 2));

        $r = (int) max(0, $r * (1 - $amount));
        $g = (int) max(0, $g * (1 - $amount));
        $b = (int) max(0, $b * (1 - $amount));

        return sprintf('#%02X%02X%02X', $r, $g, $b);
    }
}
