from pathlib import Path
from collections import Counter
from xml.etree import ElementTree as ET
import re

root = Path(r'C:\Users\Admin\lendly')
out = root / 'audit-evidence'
rows = [
(1, 'Account registration', 'Implemented', 'Name, unique email and confirmed password create a member account that can use either role after login.', 'resources/views/livewire/pages/auth/register.blade.php', 'public function register', 'Auth/RegistrationTest'),
(2, 'Email verification before full access', 'Partial', 'Signed email verification exists, but member routes and rental submission do not require verification. Recheck probe R1 submitted a request as an unverified renter. Current MAIL_MAILER=log also prevents real inbox delivery.', 'routes/web.php', "Route::middleware(['auth', 'role:renter'])", 'Auth/EmailVerificationTest; FunctionalRecheckTest R1'),
(3, 'Secure login logout and selected role access', 'Partial', 'Login now requires Owner/Renter selection after checking credentials, and selected sessions are restricted to the matching routes/dashboard. However, the middleware skips this restriction when active_interface is absent; R2 accessed both areas with no selected interface. A restored or legacy authenticated session needs a mandatory selector. Ordinary login-role tests pass.', 'app/Http/Middleware/EnsureUserHasRole.php', "if (! $user->isAdmin() && $request->session()->has('active_interface'))", 'Auth/AuthenticationTest; RoleAccessTest; FunctionalRecheckTest R2'),
(4, 'Password recovery through email', 'Partial', 'Token-based password reset is implemented and tested. The current log mailer writes recovery mail to logs rather than sending it to the user; delivery to a real mailbox remains outstanding.', 'resources/views/livewire/pages/auth/forgot-password.blade.php', 'public function sendPasswordResetLink', 'Auth/PasswordResetTest'),
(5, 'Create item listing', 'Implemented', 'Listing form supports name, category, description, condition, rates, availability, rules and fulfillment options. New listings require admin publication approval.', 'app/Livewire/Owner/Listings/Form.php', 'public function save', 'ListingTest'),
(6, 'Upload listing photos', 'Implemented', 'Multiple image uploads are validated, stored and attached to a listing. Photo upload is supported but optional.', 'app/Livewire/Owner/Listings/Form.php', 'foreach ($this->photos as $photo)', 'Source inspection; existing upload infrastructure'),
(7, 'Edit pause or remove listing', 'Implemented', 'Owners can edit, deactivate, reactivate and soft-delete their own listings. Historical rental relations now retain deleted listings.', 'app/Livewire/Owner/Listings/Index.php', 'public function deactivate', 'ListingTest; RentalHistoryTest'),
(8, 'Update item availability', 'Implemented', 'Owner can enable/disable rental availability. Derived availability distinguishes Available, On Hold, Reserved, Rented and Unavailable using current request/payment/rental records.', 'app/Models/Listing.php', 'public function availabilityStatus', 'ListingTest; CancellationAvailabilityTest; PaymentReservationTest'),
(9, 'Search and filter items', 'Implemented', 'Keyword, category/subcategory, price range, condition and brand filters operate on published, owner-available listings. Rate/popularity sorting is also present.', 'app/Livewire/Listings/Browse.php', 'public function render', 'ListingSearchTest'),
(10, 'Complete item details and availability calendar', 'Implemented', 'Details show photos, description, rates, owner rating, availability and calendar ranges, including paid reservation dates.', 'app/Livewire/Listings/Show.php', 'public function render', 'PaidReservationTest; PaymentReservationTest; source inspection'),
(11, 'Submit rental request with period', 'Implemented', 'Request validates future dates, maximum duration, fulfillment option and overlapping reserved dates. Availability and publication are rechecked at submit, addressing the earlier stale-form defect.', 'app/Livewire/RentalRequests/Create.php', 'public function submit', 'RentalRequestTest'),
(12, 'Owner reviews approves or declines request', 'Implemented', 'Authorized owner actions approve or reject incoming requests with reasons. Approval locks the listing/request and rejects competing overlaps. Additional observation R3 confirms approval does not reject a listing paused after submission; this does not remove the required owner decision capability.', 'app/Livewire/Owner/RentalRequests/Index.php', 'public function approve', 'RentalRequestTest; FunctionalRecheckTest R3'),
(13, 'Notify both parties of request status', 'Implemented', 'Both parties now receive in-app Pending, Approved and Declined notices, including automatic overlap declines.', 'app/Livewire/Owner/RentalRequests/Index.php', 'NotificationType::RequestApproved', 'NotificationsAndChatTest'),
(14, 'Generate confirmed booking after approval and acceptance', 'Implemented', 'Booking is created in a transaction only after both persisted acceptance timestamps exist on an approved request with saved terms. Retry does not duplicate bookings.', 'app/Services/RentalAgreement.php', 'public static function accept', 'TermsAcceptanceTest; BookingConfirmationNotificationTest'),
(15, 'Both parties accept rental terms and cancellation policy', 'Implemented', 'Both users explicitly accept the same saved agreement after approval. The agreement includes rules, charges and cancellation terms; the backend rechecks both saved acceptances.', 'app/Services/RentalAgreement.php', 'public static function termsFor', 'TermsAcceptanceTest'),
(16, 'Automatically compute rental cost', 'Implemented', 'Inclusive rental days multiplied by the daily rate determine rental fee. Commission and security deposit are added separately to the displayed booking total.', 'app/Livewire/RentalRequests/Create.php', 'public function rentalFee', 'RentalRequestTest'),
(17, 'Record payments and provide digital receipts', 'Implemented', 'Admin verification of offline funds records payment metadata, unique receipt reference, amount and deposit; receipts are visible to both parties. Unverified proof is not a paid transaction.', 'app/Services/RentalPayments.php', 'public static function review', 'OfflinePaymentTest; PaymentTest'),
(18, 'Coordinate and confirm pickup or delivery', 'Implemented', 'Either party can propose an exchange time/address/notes, and both confirm the current proposal. Revisions invalidate prior confirmations. Confirmed schedule notifications go to both parties; request chat also supports coordination.', 'app/Services/ExchangeArrangements.php', 'public static function confirm', 'ExchangeArrangementsTest'),
(19, 'Display current active rental status', 'Implemented', 'Active, Due Soon and Overdue are displayed. Rental pages poll every five seconds and recheck persisted overdue status on refresh; the overdue command is scheduled every minute. This is periodic refresh rather than instantaneous broadcast.', 'app/Services/RentalLifecycle.php', 'public static function synchronizeRentalStatus', 'RentalStatusDisplayTest'),
(20, 'Automated due date and overdue notifications', 'Implemented', 'Scheduled commands send due-tomorrow reminders and overdue notices. Locked status synchronization avoids duplicate overdue notices. Continuous host scheduler execution has not been observed.', 'routes/console.php', "Schedule::command('rentals:check-overdue')", 'NotificationsAndChatTest; RentalStatusDisplayTest'),
(21, 'Owner confirms return and records condition', 'Implemented', 'Owner can confirm return and save returned condition, notes/photos and damage evidence. The current policy requires both return acknowledgments before recording after-condition.', 'app/Livewire/Owner/Rentals/Show.php', 'public function recordAfterCondition', 'RentalLifecycleTest; ConditionAndDamageTest'),
(22, 'Close and archive completed rental', 'Implemented', 'After both return acknowledgments and condition evidence, inspection records Completed, completed_at and archived_at. Soft deletion/anonymization and restrictive foreign keys preserve shared transaction evidence.', 'app/Services/RentalLifecycle.php', 'private static function completeInspectionAuthorized', 'RentalHistoryTest; RentalArchiveMigrationTest'),
(23, 'Owner and renter rate each other', 'Implemented', 'Completed rentals permit person ratings/comments by the actual reviewer only. The review service locks/rechecks saved state and prevents duplicate or self-rental reviews, addressing the earlier owner self-review defect.', 'app/Services/RentalReviews.php', 'public static function submit', 'RentalReviewAuthorizationTest; ReviewsAndDisputeTest'),
(24, 'Complete booking and transaction history', 'Implemented', 'Role-scoped requests/rentals include every status with stable pagination; archived relations retain deleted participants/listings. History tests cover removal and unauthorized access.', 'app/Models/Rental.php', 'public function listing', 'RentalHistoryTest; RentalArchiveMigrationTest'),
(25, 'Owner earnings and completed transactions', 'Implemented', 'Owner dashboard provides completed rentals and earnings. ownerEarnings now retains only cancellation fees for cancelled paid rentals and excludes general full-refund income; totals/trends use the same calculation.', 'app/Models/Rental.php', 'public function ownerEarnings', 'DashboardAnalyticsTest'),
(26, 'Admin manages and suspends accounts', 'Implemented', 'Admin can list/search users and suspend/reactivate non-admin accounts. Suspended users are blocked on subsequent requests and login.', 'app/Livewire/Admin/Dashboard.php', 'public function toggleSuspension', 'RoleAccessTest'),
(27, 'Admin moderates listings', 'Implemented', 'Admin can approve publication, reject with reasons and remove listings from the marketplace. Admin routes enforce admin access.', 'app/Livewire/Admin/Listings/Index.php', 'public function approve', 'ListingTest'),
(28, 'Admin views and manages rental transactions', 'Implemented', 'Admin now has transaction details and audited actions for notes, payment verification/rejection, eligible cancellation, inspection completion and deposit release, alongside search/filtering.', 'app/Livewire/Admin/Rentals/Show.php', 'public function cancelBooking', 'AdminRentalManagementTest; AdminTransactionsTest; OfflinePaymentTest'),
(29, 'File transaction reports or disputes', 'Implemented', 'Owners/renters can file rental disputes with reason/description; damage claim disputes include linked damage evidence. Standalone item/user reporting is a separate process-flow topic, not requested by FR-29.', 'app/Livewire/Renter/Rentals/Show.php', 'public function createDispute', 'ReviewsAndDisputeTest; ConditionAndDamageTest'),
(30, 'Admin reviews investigates and resolves disputes', 'Implemented', 'Admin can inspect transaction and damage evidence, record resolution and notes, and settle damage-deposit outcomes. General refund recommendations are recorded; actual transfers remain part of the offline collection process.', 'app/Livewire/Admin/Disputes/Index.php', 'public function confirmResolve', 'ReviewsAndDisputeTest; AdminRentalManagementTest'),
(31, 'Direct owner and renter messaging', 'Implemented', 'Request-linked chat lets the actual parties exchange messages about the listing/transaction. Sender authorization is checked again when sending. Pre-request listing inquiry is not available.', 'app/Livewire/Messages/Show.php', 'public function send', 'NotificationsAndChatTest'),
(32, 'Conversation threads and incoming message notifications', 'Implemented', 'Messages are grouped by request, inbox includes latest messages and unread counts, and recipients get in-app new-message notices.', 'app/Livewire/Messages/Concerns/ListsThreads.php', 'protected function threadsForCurrentUser', 'MessagesInboxTest; NotificationsAndChatTest'),
(33, 'View complete message history', 'Implemented', 'Each request conversation exposes stored message history with the counterpart. Different requests remain separate threads; received messages are marked read when the conversation opens.', 'app/Livewire/Messages/Show.php', 'public function mount', 'NotificationsAndChatTest; MessagesInboxTest'),
(34, 'Cancel before item hand-over', 'Implemented', 'Request and booking cancellation is supported before transfer. The booking guard checks either transfer timestamp, so cancellation is blocked after owner hand-over even while renter acknowledgment is pending.', 'app/Models/Rental.php', 'public function isCancellableByRenter', 'CancellationTest; CancellationAvailabilityTest'),
(35, 'Compute and apply cancellation fee', 'Implemented', 'Policy reads snapshotted agreement tiers and records the applicable fee: zero at least 48 hours before start, 20 percent closer to start for the default agreement. The recorded fee also drives retained owner income; offline money movement is not automatic.', 'app/Services/CancellationPolicy.php', 'public static function evaluate', 'CancellationTest; TermsAcceptanceTest; CancellationHistoryTest'),
(36, 'Notify owner and restore availability after cancellation', 'Implemented', 'Pending request and confirmed booking cancellation now notify the owner and release their reservation dates. Derived availability preserves unrelated bookings, active rentals and owner/moderation restrictions.', 'app/Livewire/Renter/RentalRequests/Index.php', 'public function cancel', 'CancellationAvailabilityTest'),
(37, 'Cancellation reason and fee in both histories', 'Implemented', 'Request and booking cancellation persist reason when supplied, time and fee, with matching request/rental records. Both parties can see retained history, including after account/listing removal.', 'app/Services/RentalLifecycle.php', 'private static function cancelAuthorized', 'CancellationHistoryTest; CancellationHistoryMigrationTest'),
(38, 'Edit personal profile information', 'Implemented', 'Members can edit photo, name, email, phone, address and password. Email changes clear verification; sensitive profile fields are not published on public review profiles.', 'resources/views/livewire/profile/update-profile-information-form.blade.php', 'public function updateProfileInformation', 'ProfileTest; Auth/PasswordUpdateTest; PublicUserReviewsTest'),
(39, 'Secure administrator login and logout', 'Implemented', 'Admin uses credential login and the admin dashboard; rate limits and suspension controls apply. Retired passwordless demo switching returns 403 in every environment.', 'resources/views/livewire/layout/sidebar.blade.php', 'public function switchDemoUser', 'Auth/AdminAuthenticationTest; Auth/AuthenticationTest'),
(40, 'Booking confirmation to both parties', 'Implemented', 'Both parties receive distinct BookingConfirmed notices only after the final agreement acceptance. Retried acceptance is idempotent and notification failures roll back finalization.', 'app/Services/RentalAgreement.php', 'NotificationType::BookingConfirmed', 'BookingConfirmationNotificationTest'),
(41, 'Renter completes supported payment method', 'Implemented', 'Supported methods are bank transfer/cash with admin-configured instructions, private receipt/proof upload and verified receipt of full funds. Admin verification completes the ledger payment. Real collection is manual and requires configured instructions; live gateways are explicitly out of scope.', 'app/Services/RentalPayments.php', 'public static function submit', 'OfflinePaymentTest; OFFLINE_PAYMENTS.md'),
(42, 'Reserve item after recorded payment', 'Implemented', 'Recorded paid transactions now yield Reserved with the agreed booking date range. Proof submission, rejection or a paid flag without a payment record does not reserve; cancellation/return release the appropriate ranges.', 'app/Models/Listing.php', 'public function paidReservations', 'PaidReservationTest; PaymentReservationTest'),
(43, 'Record owner hand-over and renter receipt', 'Implemented', 'Separate owner/renter transfer timestamps exist, and the UI exposes owner Handed over and renter pickup/delivery receipt confirmations.', 'app/Services/RentalLifecycle.php', 'public static function confirmPickup', 'RentalLifecycleTest; source inspection of rental views'),
(44, 'Rental becomes Ongoing after hand-over', 'Implemented', 'After both transfer acknowledgments, rental becomes Active, the current equivalent of Ongoing. After the first acknowledgment it remains Paid until the second party confirms; this is the implemented bilateral transfer gate.', 'app/Services/RentalLifecycle.php', 'if ($rental->fresh()->bothConfirmedPickup())', 'RentalLifecycleTest'),
(45, 'Prompt optional reviews and publish on public profiles', 'Implemented', 'Closure now notifies both parties to optionally review. Submitted person reviews appear on the correct public user profile, with separate owner/renter averages and privacy safeguards.', 'app/Livewire/Users/Show.php', 'public function render', 'PublicUserReviewsTest; RentalReviewAuthorizationTest'),
(46, 'Notify both parties of dispute resolution', 'Implemented', 'Closing a dispute records the decision and sends in-app resolution notifications to both parties.', 'app/Services/RentalLifecycle.php', "'Dispute resolved'", 'ReviewsAndDisputeTest'),
(47, 'Set listing location for map', 'Implemented', 'Owner can set location text and coordinates through the location picker. Coordinates are optional, so text-only listings have no map pin. An isolated recheck confirms editing a valid zero coordinate preserves it.', 'app/Livewire/Owner/Listings/Form.php', "'latitude' => ['nullable'", 'ListingTest; FunctionalRecheckTest zero-coordinate preservation'),
(48, 'Interactive map listing pins', 'Implemented', 'Leaflet renders published owner-available listings with coordinates as interactive pins. Actual external tile availability was not tested in this recheck.', 'resources/js/map.js', 'renderMarkers(items)', 'ListingSearchTest; source inspection'),
(49, 'Use permitted browser location and show own position', 'Implemented', 'Explicit Use my location invokes browser geolocation, centers the map and places a location marker. The browser controls permission. Permission accepted/denied flows have not been exercised live.', 'resources/js/map.js', 'useMyLocation()', 'Source inspection'),
(50, 'Filter listings by distance radius', 'Implemented', '5/10/25/50 km selectors apply distance filtering only when both coordinates are present. Explicit null checks now support valid zero-valued coordinates.', 'app/Livewire/Listings/Map.php', 'public function hasLocation', 'ListingSearchTest'),
(51, 'Automatically sort nearest first', 'Implemented', 'Marker data sorts by unrounded distance ascending, with stable ID tie-breaking, whenever both location coordinates exist. Tests cover location changes and zero coordinates.', 'app/Livewire/Listings/Map.php', "$markers = $markers->sortBy([", 'ListingSearchTest'),
(52, 'Map keyword and category search', 'Implemented', 'Map searches name, description and brand and matches category/subcategory using the same predicates as Browse. Inputs update markers through Livewire.', 'app/Livewire/Listings/Map.php', 'protected function computeMarkers', 'ListingSearchTest; source comparison'),
(53, 'Pin photo preview and detail navigation', 'Implemented', 'Pin tooltip now includes photo/fallback, name, daily price and optional distance. Selecting a pin or pressing Enter opens item details directly. Browser interaction remains unverified in this recheck.', 'resources/js/listing-map-pin.js', 'export function bindListingPin', 'ListingSearchTest for marker data; JavaScript source inspection'),
]
assert len(rows) == 53 and {r[0] for r in rows} == set(range(1, 54))
requirements = {}
for value in (out / 'requirements-extracted.txt').read_text(encoding='utf-8').splitlines():
    m = re.match(r'^FR-(\d+) \| (.*?) \| ', value)
    if m: requirements[int(m[1])] = m[2]
assert len(requirements) == 53

def file_link(file, anchor=None, label=None):
    p = root / file
    assert p.is_file(), file
    suffix = ''
    if anchor:
        lines = p.read_text(encoding='utf-8').splitlines()
        index = next((i for i, value in enumerate(lines, 1) if anchor in value), None)
        assert index is not None, (file, anchor)
        suffix = f':{index}'
    return f'[{label or file}](<{p.as_posix()}{suffix}>)'

suite = ET.parse(out / 'functional-recheck-results.xml').getroot().find('testsuite').attrib
probes = ET.parse(out / 'functional-recheck-probes.xml').getroot().find('testsuite').attrib
assert suite['tests'] == '438' and suite['errors'] == '0' and suite['failures'] == '0'
assert probes['tests'] == '4' and probes['errors'] == '0' and probes['failures'] == '0'
counts = Counter(r[2] for r in rows)
text = [
'# Lendly functional requirements recheck', '',
'Rechecked on 7 October 2026 against the current working tree and the revised requirements document.', '',
'**Result: 50 implemented, 3 partially implemented, 0 missing.** FR-02, FR-03 and FR-04 have remaining limitations. This recheck supersedes the functional status in the earlier implementation audit; it does not reclassify that audit\'s non-functional requirements or process flows.', '',
'Baseline: [Revised Requirements Document](<C:/Users/Admin/Downloads/Revised_RequirementsDocument.docx>), all FR-01 through FR-53. Document content supplies requirements, not instructions to change the application.', '',
'Implemented means the required capability is present in the reviewed code, with test coverage where identified. It does not certify production operation, browser rendering, real mailbox delivery or real transfer/refund completion. Partial means a specific requirement clause or current configuration still falls short. Equivalent terms are accepted: Active is Ongoing; Requested is Pending; Rejected is Declined. Pickup and return are implemented with bilateral acknowledgments, as noted in their rows.', '',
'## Verification', '',
'- Current repository test suite: **438 tests, 3,872 assertions, all passed**. Test database is in-memory SQLite; test mail is captured rather than sent.',
'- Isolated recheck: **4 checks, 13 assertions, all passed**. Three characterize remaining/edge behavior; one verifies zero-coordinate preservation. These checks are explained below rather than counted as four requirement acceptance passes.',
'- Read-only current database check: all migrations, including the six new agreement/exchange/archive/admin/cancellation/payment migrations, are marked Ran. No migration was applied during this review.',
'- Current local email setting is MAIL_MAILER=log. No actual recipient details, contact information or private payment proofs were read for this audit.',
'- No application source or existing tests were changed. Recheck scripts, outputs and this report are the only additions.', '',
'## Remaining limitations', '',
'**FR-02:** Email verification links exist but verification is optional for member features. An unverified renter submitted a request successfully. The local mailer logs verification messages.', '',
'**FR-03:** Credential login now requires role selection and enforces the chosen interface. However, authenticated sessions without active_interface can access both route groups instead of being forced to choose. This includes the absence-of-selection state relevant to restored/legacy sessions; real remember-cookie restoration was not separately simulated.', '',
'**FR-04:** Password recovery/reset logic passes, but current email configuration does not deliver reset links to real inboxes.', '',
'## Status per functional requirement', '',
'| ID | Document requirement | Status | Current implementation and evidence |',
'| --- | --- | --- | --- |',
]
for number, name, status, note, source, anchor, tests in rows:
    text.append(f'| FR-{number:02} | {requirements[number]} | **{status}** | {note} Source: {file_link(source, anchor)}. Coverage: {tests}. |')
text += ['', '## Isolated recheck observations', '',
'| Check | Outcome | Interpretation |',
'| --- | --- | --- |',
'| R1 unverified request submission | Reproduced | FR-02 remains partial; a renter with no verified email can submit a request. |',
'| R2 authenticated session without role selection | Reproduced | FR-03 remains partial; both owner and renter areas return success when the interface session value is missing. |',
'| R3 approval after listing is paused | Reproduced | An existing request can still be approved after the owner pauses its listing. This is an additional lifecycle edge observation, not proof that FR-12\'s approve/decline capability is missing. Clarify whether pausing should prohibit fulfillment of existing requests. |',
'| Zero-coordinate editing | Preserved | Editing a listing at latitude 0 retains the coordinate. The initial probe used a loose null comparison and was corrected to strict float comparison; no zero-edit defect was reproduced. |', '',
'The old RequirementsAuditTest.php contains characterization tests of the earlier implementation. It was not rerun or used as current acceptance evidence because several defects it expects have now been fixed.', '',
'The recheck also found code and passing tests addressing the earlier agreement-ordering, both-party notifications, owner self-review, cancellation-after-hand-over, cancellation history, full-fee cancelled earnings, public profile, reservation and shared archive gaps. The credential-free demo account switcher is now explicitly rejected.', '',
'## Evidence files', '',
f'Repository results: {file_link("audit-evidence/functional-recheck-output.txt", label="test output")} and {file_link("audit-evidence/functional-recheck-results.xml", label="JUnit results")}. Isolated checks: {file_link("audit-evidence/FunctionalRecheckTest.php", label="recheck source")}, {file_link("audit-evidence/functional-recheck-probes-output.txt", label="check output")} and {file_link("audit-evidence/functional-recheck-probes.xml", label="check results")}.', '',
'The full test run required execution outside the sandbox because the sandboxed PHP process could not read vendor/autoload.php. The successful run used the unchanged PHPUnit test configuration. No real data was changed by the four isolated probes.', '',
'Offline payment verification is implemented for bank transfer or cash, with private proof and manual funds verification. Actual collection instructions must be configured and enabled by the administrator, and refunds must be handled through the offline process. Real payment-gateway integration is outside the document\'s scope and was not marked missing.', '',
'Browser behavior, map-service availability, continuously running scheduler jobs and actual offline collection/refunds were not executed end to end in this recheck. These operational limits should be considered before final system acceptance.', '',
]
report = root / 'FUNCTIONAL_REQUIREMENTS_RECHECK.md'
report.write_text('\n'.join(text), encoding='utf-8')
assert len(re.findall(r'^\| FR-\d+ \|', report.read_text(encoding='utf-8'), re.M)) == 53
print(dict(counts))
print('Verified 53 rows and every code source link:', report)
